#!/usr/bin/env php
<?php

@include('.env.php');
error_reporting(E_STRICT);
require 'vendor/autoload.php';

use Mapstorming\Commands\AddCity;
use Mapstorming\Commands\DeleteCity;
use Mapstorming\Commands\EditCity;
use Mapstorming\Commands\ExportMbtiles;
use Mapstorming\Commands\ProcessDatasets;
use Mapstorming\Commands\Scrap;
use Symfony\Component\Console\Application;

$process = new ProcessDatasets();
$application = new Application();
$application->setName('Mapstorming');
$application->setDefaultCommand($process->getName());
$application->setVersion(0.1);

$application->add($process);
$application->add(new AddCity());
$application->add(new EditCity());
$application->add(new DeleteCity());
$application->add(new ExportMbtiles());
$application->add(new Scrap());

$application->run();